comment: false
coverage:
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
github_checks:
  annotations: true
ignore:
  - "noxfile.py"
